swagger: '2.0'
info:
  title: Peach API TEST
  description: '`k-peach`의 RESTfull API dev 문서.'
  version: 1.0.0
  license:
    name: MIT
  contact:
    name: Peach
    email: tjdwls0607@naver.com
    url: www.k-peach.io/
host: api.k-peach.io
basePath: '/'
tags:
  - name: 'thumbnail'
    description: 'Thumbnail image(.jpg) about packaged video'
  - name: 'perfect-voice'
    description: 'Voice recorded by voice actor'
  - name: 'user-voice'
    description: 'Voice recorded by user'
schemes:
  - https
paths:
  /thumbnail/:
    get:
      tags:
        - thumbnail
      summary: Get thumbnail images in S3.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: The images list.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              data:
                type: object
                properties:
                  name:
                    type: string
                    example: 1
                  format:
                    type: string
                    example: jpg
                  path:
                    type: string
                    example: data.k-peach.io/thumbnail/1.jpg
                  size:
                    type: number
                    example: 2846729
                  lastModified:
                    type: string
                    example: '2021-07-05T09:55:52.000Z'
  /thumbnail/{name}:
    get:
      tags:
        - thumbnail
      summary: Get a thumbnail image in S3.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          required: true
          description: The name of a iamge to get
          type: string
      responses:
        200:
          description: A image.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              data:
                type: object
                properties:
                  name:
                    type: string
                    example: 1
                  format:
                    type: string
                    example: jpg
                  path:
                    type: string
                    example: data.k-peach.io/thumbnail/1.jpg
                  size:
                    type: number
                    example: 2846729
                  lastModified:
                    type: string
                    example: '2021-07-05T09:55:52.000Z'
        400:
          description: The specified image name is invalid or non-existent.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              errorMessage:
                type: string
        default:
          description: Unexpected error
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              errorMessage:
                type: string
  /perfect-voice/:
    get:
      tags:
        - perfect-voice
      summary: Get perfect-voice audio in S3.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: The audio files list.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              data:
                type: object
                properties:
                  name:
                    type: string
                    example: Hello
                  format:
                    type: string
                    example: wav
                  path:
                    type: string
                    example: data.k-peach.io/perfect-voice/Hello.wav
                  size:
                    type: number
                    example: 2846729
                  lastModified:
                    type: string
                    example: '2021-07-05T09:55:52.000Z'
  /perfect-voice/{name}:
    get:
      tags:
        - perfect-voice
      summary: Get a poerfect-voice audio in S3.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          required: true
          description: The name of a audio file to get
          type: string
      responses:
        200:
          description: A audio file.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              data:
                type: object
                properties:
                  name:
                    type: string
                    example: Hello
                  format:
                    type: string
                    example: wav
                  path:
                    type: string
                    example: data.k-peach.io/perfect-voice/Hello.wav
                  size:
                    type: number
                    example: 2846729
                  lastModified:
                    type: string
                    example: '2021-07-05T09:55:52.000Z'
        400:
          description: The specified audio file name is invalid or non-existent.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              errorMessage:
                type: string
        default:
          description: Unexpected error
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              errorMessage:
                type: string
  /user-voice/:
    get:
      tags:
        - user-voice
      summary: Get user-voice audio in S3.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: The audio files list.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              data:
                type: object
                properties:
                  name:
                    type: string
                    example: '2021-07-10'
                  format:
                    type: string
                    example: wav
                  path:
                    type: string
                    example: data.k-peach.io/user-voice/2021-07-10.wav
                  size:
                    type: number
                    example: 2846729
                  lastModified:
                    type: string
                    example: '2021-07-05T09:55:52.000Z'
    post:
      tags:
        - user-voice
      summary: Get a user-voice audio in S3.
      description: You should set up the attribute of form tag like `name="uploadFile"` and file format is `.wav`
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: 'uploadedFile'
          in: 'formData'
          description: file to upload `.wav`
          required: true
          type: 'file'
      responses:
        200:
          description: A audio file.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              data:
                type: object
                properties:
                  name:
                    type: string
                    example: '2021-07-10'
                  format:
                    type: string
                    example: wav
                  path:
                    type: string
                    example: data.k-peach.io/user-voice/2021-07-10.wav
                  size:
                    type: number
                    example: 2846729
                  mimetype:
                    type: string
                    example: 'audio/wav'
        400:
          description: The specified audio file name is invalid or non-existent.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              errorMessage:
                type: string
        default:
          description: Unexpected error
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              errorMessage:
                type: string
  /user-voice/{name}:
    get:
      tags:
        - user-voice
      summary: Get a user-voice audio in S3.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          required: true
          description: The name of a audio file to get
          type: string
      responses:
        200:
          description: A audio file.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              data:
                type: object
                properties:
                  name:
                    type: string
                    example: '2021-07-10'
                  format:
                    type: string
                    example: wav
                  path:
                    type: string
                    example: data.k-peach.io/user-voice/2021-07-10.wav
                  size:
                    type: number
                    example: 2846729
                  lastModified:
                    type: string
                    example: '2021-07-05T09:55:52.000Z'
        400:
          description: The specified audio file name is invalid or non-existent.
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              errorMessage:
                type: string
        default:
          description: Unexpected error
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              errorMessage:
                type: string
